function objects = setup()
    %%% General setup function
    % Outputs: objects(struct) - contains all object types of sensors and
    % controllers
    
    % Obtain objects for hardware
    [nano_objects] = setupArduino();
    [camera] = setupCamera();
    [gps] = setupGps();
    [lidar] = setupLidar();
    [joystick] = setupJoystick();

    % Seperate Arduino objects/connections
    nano = nano_objects.nano;
    imu = nano_objects.imu;
    sharpIR = nano_objects.sharpIR;
    sonar = nano_objects.sonar;
    tilt = nano_objects.tilt;
    pan = nano_objects.pan;
    steer = nano_objects.steer;
    throttle = nano_objects.throttle;
    
    % Package objects
    objects = struct(...
        "nano",nano,...
        "sharpIR",sharpIR,...
        "sonar",sonar,...
        "tilt",tilt,...
        "pan",pan,...
        "steer",steer,...
        "throttle",throttle,...
        "camera",camera,...
        "gps",gps,...
        "lidar",lidar,...
        "joystick",joystick);
end